### ISSUE TITLE
请作者能够回复一下 ？

### ISSUE THREAD

**Issue by Sparksfire** [dotbalo/kubernetes-guide#5]
请问书中资源：`git clone https://gitee.com/dukuan/k8s-ha-install.git down`下来的是啥？

再请问书中，`cd /root/k8s-install/dashboard`  在这里提到的这些资源呢 ？其他的就懒得提了，不明不白的，既然在书中写到了，又不提供，吃相真难看啊！

**Comment by dotbalo** [comment]
大哥，你git 不会用别说我们不提供好吧？ 在2022年07月30日 23:35，weirdo 写道： 

请问书中资源：git clone https://gitee.com/dukuan/k8s-ha-install.git down下来的是啥？

再请问书中，cd /root/k8s-install/dashboard  在这里提到的这些资源呢 ？其他的就懒得提了，不明不白的，既然在书中写到了，又不提供，吃相真难看啊！



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/dotbalo/kubernetes-guide/issues/5",

"url": "https://github.com/dotbalo/kubernetes-guide/issues/5",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by dotbalo** [comment]
> 

大哥，你git 不会用，别说我们不提供好吧，请你自己搞清楚再来提问。
